package com.pharius.inventoryapp.inventoryapp.Entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product { //Product entity

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long id;
    private String name;
    private int stock;

}
