package com.pharius.inventoryapp.inventoryapp.Models.RestockModels;

import java.util.List;

import com.pharius.inventoryapp.inventoryapp.Models.Establishment;
import com.pharius.inventoryapp.inventoryapp.Models.ProductModels.Product;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

public class Restock {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long restockId;


    @OneToMany // One restock can have many products - One product can be restocked many times
    private List<Product> restockProducts; //List of products to restock   

    @OneToMany // One restock can belong to one establishment - Every establishment has a different restock
    private Establishment establishment; //Establishment to restock



    
}
