package com.pharius.inventoryapp.inventoryapp.Models.RestockModels;

import java.util.List;

import com.pharius.inventoryapp.inventoryapp.Models.EstablishmentModels.Establishment;
import com.pharius.inventoryapp.inventoryapp.Models.ProductModels.Product;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;


@Entity
public class Restock {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long restockId;

    @ManyToMany // One restock can have many products - One product can be restocked many times
    @JoinTable(
        name="restock_product",
        joinColumns = @JoinColumn(name = "restock_id"),
        inverseJoinColumns = @JoinColumn(name = "product_id")
    )
    private List<Product> restockProducts; //List of products to restock   

    @ManyToOne // One restock can belong to one establishment - Every establishment has many restocks
    @JoinColumn(name = "establishment_id", nullable = false) // foreign key establishment_id
    private Establishment establishment; //Establishment to restock



    
}
