package com.pharius.inventoryapp.inventoryapp.Models.RestockModels;

import java.time.LocalDateTime;
import java.util.Set;

import com.pharius.inventoryapp.inventoryapp.Models.EstablishmentModels.Establishment;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Restock {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long restockId;

    @ManyToOne // One restock can belong to one establishment - Every establishment has many
               // restocks
    @JoinColumn(name = "establishment_id", nullable = false) // foreign key establishment_id
    private Establishment establishment; // Establishment to restock

    private LocalDateTime localDateTime; // Date and time of restock

    @OneToMany(mappedBy="restock", cascade= CascadeType.ALL, orphanRemoval = true)
    private Set<RestockProduct> restockProducts;

    public Restock(Restock restock) {
        this.restockId = restock.getRestockId();
        this.establishment = restock.getEstablishment();
        this.localDateTime = restock.getLocalDateTime();
    }

}
