package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;

import com.pharius.inventoryapp.inventoryapp.Models.Establishment;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table
public class Inventory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long inventoryId;

    @OneToOne // One inventory can have one establishment - Every establishment has one inventory
    @JoinColumn(name = "establishment_id", nullable = false, unique = true) // Foreign key establishment_id
    private Establishment establishment;

}
