package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name="product", uniqueConstraints = {@UniqueConstraint(columnNames = {"name"})}) // Table name and unique constraints
public class Product { //Product entity

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long productId;

    @NotBlank(message = "Product name is required")
    @Column(nullable = false)
    private String name;

    @ManyToOne // One product can have one type - One type can be assigned to many products
    @JoinColumn(name = "type_of_product_id", nullable = false) // foreign key type_of_product_id
    private TypeOfProduct typeOfProduct;  // Type of product
    
}
