package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name="product", uniqueConstraints = {@UniqueConstraint(columnNames = {"name"})})
public class Product { //Product entity

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long productId;

    @Column(nullable = false)
    private String name;

    @ManyToOne // One product can belong to one inventory - Every inventory has many products
    @JoinColumn(name = "inventory_id", nullable = false) // foreign key inventory_id
    private Inventory inventory;

    private int quantity; // quantity of products in stock per inventory

    @ManyToOne // One product can have one type - One type can be assigned to many products
    @JoinColumn(name = "type_of_product_id", nullable = false) // foreign key type_of_product_id
    private TypeOfProduct typeOfProduct;  // Type of product
    

}
