package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;

import com.pharius.inventoryapp.inventoryapp.Models.Establishment;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table
public class Stock {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long stockId;

    @ManyToOne // One product can have many stocks - One stock belongs to one product
    private Product product;

    @ManyToOne // One stock can belong to one establishment - Every establishment has a different stock
    private Establishment establishment;

    
    private int quantity;




}
