package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;


@Entity
@Data
public class TypeOfProduct {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long typeOfProductId;

    @Column(nullable = false, unique = true)
    private String name;

}
