package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TypeOfProduct {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long typeOfProductId;

    @NotBlank(message = "Type of product name is required")
    @Column(nullable = false, unique = true)
    private String name;


    public TypeOfProduct(TypeOfProduct typeOfProduct) {
        this.typeOfProductId = typeOfProduct.getTypeOfProductId();
        this.name = typeOfProduct.getName();
    }



}
