package com.pharius.inventoryapp.inventoryapp.Models.ProductModels;

import java.lang.reflect.Type;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TypeOfProduct {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long typeOfProductId;

    @Column(nullable = false, unique = true)
    private String name;


    public TypeOfProduct(TypeOfProduct typeOfProduct) {
        this.typeOfProductId = typeOfProductId;
        this.name = name;
    }



}
