package com.pharius.inventoryapp.inventoryapp.Models.EstablishmentModels;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table
public class Establishment {
  
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID autogenerated method
    private Long establishmentId;
    @NotBlank(message = "Establishment name is required")
    @Size(min = 4, message = "Establishment name must be at least 4 characters")
    private String name;

    @NotBlank(message = "Establishment location is required")
    @Size(min = 4, message = "Establishment location must be at least 4 characters")
    private String location;


}
